// This file is processed at build time to generate the known icons list
// The actual icon list is generated by a build script or Astro's build process

// Fallback list of known icons (will be replaced at build time)
let knownIconsCache: string[] = [
	'CPlusPlus',
	'algolia',
	'angular',
	'apollo',
	'apple_shortcuts',
	'arrow-left',
	'astro',
	'azure',
	'azure_devops',
	'bars',
	'bash',
	'bitwarden',
	'bootstrap',
	'briefcase',
	'cloudflare',
	'code',
	'codeium',
	'copilot',
	'css',
	'cursor',
	'cursor-ia',
	'dashboard',
	'deepseek',
	'dependabot',
	'docker',
	'docusaurus',
	'envelope',
	'eslint',
	'excel',
	'facebook',
	'figma',
	'firebase',
	'flask',
	'gatsby',
	'git',
	'github',
	'github-svg',
	'gitlab',
	'google_apps_script',
	'google_cloud',
	'google_sheets',
	'graphql',
	'heroku',
	'html',
	'info',
	'instagram',
	'java',
	'javascript',
	'json',
	'linkedin',
	'logo',
	'markdown',
	'md',
	'mongo',
	'moon',
	'mysql',
	'neo4j',
	'neo4j_cypher',
	'nestjs',
	'netlify',
	'nextauth',
	'nextjs',
	'node',
	'nodejs',
	'npm',
	'obsidian',
	'paperplane',
	'person',
	'php',
	'pip',
	'power_apps',
	'power_automate',
	'power_bi',
	'power_platform',
	'power_query',
	'powerpoint',
	'powershell',
	'preact',
	'prettier',
	'project',
	'python',
	'react',
	'rocket',
	'sass',
	'snyk',
	'sql',
	'sun',
	'tailwind',
	'twitter',
	'typescript',
	'vba',
	'vercel',
	'visio',
	'vitejs',
	'vs_code',
	'whatsapp',
	'windsurf-logo',
	'wordpress',
	'xmark',
	'yarn',
	'youtube',
	'zod',
];

/**
 * Gets all known icon names from the src/icons directory
 * @returns Array of icon names (without .svg extension)
 */
export function getKnownIcons(): string[] {
	return knownIconsCache;
}

/**
 * Checks if an icon name is known (exists in the icons directory)
 * @param iconName - The icon name to check (with or without .svg extension)
 * @returns boolean indicating if the icon is known
 */
export function isKnownIcon(iconName: string): boolean {
	if (!iconName) return false;

	// Remove .svg extension if present
	const cleanIconName = iconName.replace(/\.svg$/, '');

	return knownIconsCache.includes(cleanIconName);
}

/**
 * Gets the clean icon name (removes .svg extension)
 * @param logoFileName - The logo file name from frontmatter
 * @returns Clean icon name or null if no logo file name provided
 */
export function getSkillIconName(logoFileName: string | null): string | null {
	if (!logoFileName) return null;
	// Remove .svg extension if present
	return logoFileName.replace(/\.svg$/, '');
}

/**
 * Gets the icon name for a skill by looking up the skill name in the mapping
 * @param skillName - The skill name to look up
 * @returns Icon name or null if not found
 * @deprecated This function is no longer used. Skills are now looked up directly from the skills collection.
 */
export function getSkillIconByName(skillName: string): string | null {
	if (!skillName) return null;
	// This function is deprecated - skills are now looked up directly from the skills collection
	// in the SkillPill component for better error handling and real-time updates
	return null;
}

/**
 * Checks if an icon should be shown (exists and is known)
 * @param iconName - The icon name to check
 * @returns boolean indicating if the icon should be shown
 */
export function shouldShowIcon(iconName: string): boolean {
	return isKnownIcon(iconName);
}

// Build-time function to update the icons list
// This would be called by a build script or Astro plugin
export function updateKnownIcons(icons: string[]) {
	knownIconsCache = icons;
}
